export const DOCUMENT_REFERENCE_TYPES = Object.freeze({
    GOODS_ISSUE: 'SAL',
    GOODS_RECEIPT: 'REC',
    STOCK_ADJUSTMENT: 'AJU',
    WASTE_STOCK_ADJUSTMENT: 'AJU-MER',
    WASTE_ISSUE: 'SAL-MER'
});
