export const GOODS_RECEIPT_DETAIL_CHANGE_TYPES = Object.freeze({
    QUANTITY: 'QUANTITY',
    COST: 'COST',
    QUANTITY_AND_COST: 'QUANTITY_AND_COST',
    CANCELLATION: 'CANCELLATION'
});

export const GOODS_RECEIPT_DETAIL_CHANGE_REASON_NAMES = Object.freeze({
    CORRECTION: 'Corrección de detalle de compra',
    CANCELLATION: 'Cancelación de detalle de compra'
});

const GOODS_RECEIPT_DETAIL_CHANGE_REASON_BY_TYPE = Object.freeze({
    [GOODS_RECEIPT_DETAIL_CHANGE_TYPES.QUANTITY]: GOODS_RECEIPT_DETAIL_CHANGE_REASON_NAMES.CORRECTION,
    [GOODS_RECEIPT_DETAIL_CHANGE_TYPES.COST]: GOODS_RECEIPT_DETAIL_CHANGE_REASON_NAMES.CORRECTION,
    [GOODS_RECEIPT_DETAIL_CHANGE_TYPES.QUANTITY_AND_COST]: GOODS_RECEIPT_DETAIL_CHANGE_REASON_NAMES.CORRECTION,
    [GOODS_RECEIPT_DETAIL_CHANGE_TYPES.CANCELLATION]: GOODS_RECEIPT_DETAIL_CHANGE_REASON_NAMES.CANCELLATION
});

export const getGoodsReceiptDetailChangeReasonName = (changeType) => (
    GOODS_RECEIPT_DETAIL_CHANGE_REASON_BY_TYPE[changeType]
);
