export const INVENTORY_MOVEMENT_TYPES = Object.freeze({
    ENTRY: 'ENTRY',
    ISSUE: 'ISSUE',
    ADJUSTMENT: 'ADJUSTMENT'
});

export const INVENTORY_REFERENCE_TYPES = Object.freeze({
    GOODS_RECEIPT: 'GOODS_RECEIPT',
    GOODS_ISSUE: 'GOODS_ISSUE',
    PURCHASE_REQUISITION: 'PURCHASE_REQUISITION'
});

export const STOCK_ADJUSTMENT_TYPES = Object.freeze({
    INCREASE: 'INCREASE',
    DECREASE: 'DECREASE'
});

export const STOCK_ADJUSTMENT_STATUS_NAMES = Object.freeze({
    APPLIED: 'APPLIED'
});
